**items**

In [16]:
import json
import pandas as pd
fd = open('inventory.json','r')
fetch = fd.read()
fd.close()

items = json.loads(fetch)
df = pd.DataFrame(items).T
df

                                name price quantity rating discount   category
18971                      parachute    40      170    4.2        2        oil
18972                    boatrokerzz   160      291    4.5        5  headphone
18973                        Jim Jam    35      100    4.6        1   biscuits
18974                          Bingo    20      143      4        0      chips
18975        Britannia Little Hearts    20      100    3.8        3      chips
18976          Cadbury Oreo Choclate    80      200    4.3        4  choclates
18977              Parle Hide & Seek    50       60    3.7        0   biscuits
18978           Sunfeast Mom's Magic    40      130    4.4        2   biscuits
18979          Sunfeast Dark Fantasy   120      200    4.7        7   biscuits
18980        Farmlite Fibre Biscuits   180      158    4.2        5   biscuits
18981             Dairy Milk Crackle    45      150    4.5        3  choclates
18982  Bournville Cranberry Choclate   100       70      4        5  choclates
18983          Cornitos Nacho Crisps    35      196    3.5        0      chips
18984     Bingo Mad Angles Peri Peri    20      170    3.7        2      chips
18985            Lay's Cream & Onion    35      240    4.2        5      chips
18986             Lay's Indian Magic    35      200    4.1        3      chips
18987           Lay's Classic Salted    35      190      4        2      chips

**bill of purchse item**

In [17]:
ui_id = str(input("Enter the id of item: "))
ui_qty=int(input("Enter the required quantity of item: "))

avl_qty=items[ui_id]['quantity']
fd = open('sales.json','r')
fetch = fd.read()
fd.close()
sales = json.loads(fetch)
sid=str(len(sales)+1)

if(avl_qty<ui_qty):
    print("Sorry, the maximum available items are ",str(avl_qty))
    choice=str(input("Do you still want to purchase, enter your choice(Yes/No): "))
    if(choice=='Yes'):
        print("The bill details for the purchase are: ")
        print("Item name: ",items[ui_id]['name'])
        print("Item price: ",str(items[ui_id]['price']))
        cost=items[ui_id]['price']*items[ui_id]['quantity']
        cost-=float((items[ui_id]['discount']/100)*cost)
        print("Total cost: ",str(cost))
        sales[sid]={'item_name':items[ui_id]['name'],'item_cost': cost, 'item_qty':items[ui_id]['quantity'], 'item_id':ui_id}
        items[ui_id]['quantity']=0
        inv = json.dumps(items)
        fd = open('inventory.json','w')
        fd.write(inv)
        fd.close()
    else:
        print("Sorry to see you go :(")
else:   
    print("The bill details for the purchase are: ")
    print("Item name: ",items[ui_id]['name'])
    print("Item price: ",str(items[ui_id]['price']))
    cost=items[ui_id]['price']*ui_qty
    cost-=float((items[ui_id]['discount']/100)*cost)
    print("Total cost: ",str(cost))
    sales[sid]={'item_name':items[ui_id]['name'],'item_cost': cost, 'item_qty':ui_qty, 'item_id':ui_id}
    items[ui_id]['quantity']-=ui_qty
    inv = json.dumps(items)
    fd = open('inventory.json','w')
    fd.write(inv)
    fd.close()

fd = open('inventory.json','r')
fetch = fd.read()
fd.close()

items = json.loads(fetch)
df = pd.DataFrame(items).T
df

Enter the id of item: 18987
Enter the required quantity of item: 2
The bill details for the purchase are:
Item name:  Lay's Classic Salted
Item price:  35
Total cost:  68.6

                                name price quantity rating discount   category
18971                      parachute    40      170    4.2        2        oil
18972                    boatrokerzz   160      291    4.5        5  headphone
18973                        Jim Jam    35      100    4.6        1   biscuits
18974                          Bingo    20      143      4        0      chips
18975        Britannia Little Hearts    20      100    3.8        3      chips
18976          Cadbury Oreo Choclate    80      200    4.3        4  choclates
18977              Parle Hide & Seek    50       60    3.7        0   biscuits
18978           Sunfeast Mom's Magic    40      130    4.4        2   biscuits
18979          Sunfeast Dark Fantasy   120      200    4.7        7   biscuits
18980        Farmlite Fibre Biscuits   180      158    4.2        5   biscuits
18981             Dairy Milk Crackle    45      150    4.5        3  choclates
18982  Bournville Cranberry Choclate   100       70      4        5  choclates
18983          Cornitos Nacho Crisps    35      196    3.5        0      chips
18984     Bingo Mad Angles Peri Peri    20      170    3.7        2      chips
18985            Lay's Cream & Onion    35      240    4.2        5      chips
18986             Lay's Indian Magic    35      200    4.1        3      chips
18987           Lay's Classic Salted    35      188      4        2      chips

**FINAL BILL**

In [18]:
inv = json.dumps(sales)
fd = open('sales.json','w')
fd.write(inv)
fd.close()

In [19]:
fd = open('sales.json','r')
sales=fd.read()
s=json.loads(sales)
fd.close()
df = pd.DataFrame(s).T
df

                   item_name item_cost item_qty item_id
1                  parachute        40        1   18971
2                boatrokerzz       160        1   18972
3         Cadbury Perk Bites       608        4   18972
4        Lay's Cream & Onion     332.5       10   18985
5    Farmlite Fibre Biscuits       171        1   18980
6   Bingo Mad Angles Classic       140        7   18974
7           Amul Butter Milk    213.84       12   18994
8          Britannia Jim Jam    103.95        3   18973
9      Cornitos Nacho Crisps       140        4   18983
10   Farmlite Fibre Biscuits       171        1   18980
11      Lay's Classic Salted      68.6        2   18987